service: its-too-damn-hot

frameworkVersion: ">=1.5.0 <2.0.0"

provider:
    name: aws
    region: eu-west-1
    runtime: python3.6

functions:
    react:
        handler: handler.react
        events:
            - iot:
                sql: "SELECT * FROM 'test/jamies'"
