service: its-too-damn-hot

frameworkVersion: ">=1.5.0 <2.0.0"

provider:
    name: aws
    runtime: aws-python3

functions:
    react:
        handler: handler.react
        events:
            - iot:
                sql: "SELECT * FROM 'officetemp'"
